flowchart TD
    C["Experience<br /> IDE & Instructions"]
    A["Control<br /> Policies OPA & CI/CD"]
    B["Best practices<br /> Docs & Examples & Tools"]

    B --> C
    A --> C 

    style A fill:#e1f5fe
    style B fill:#f3e5f5
    style C fill:#e8f5e8